### ISSUE TITLE
Add support for drop_all

### ISSUE THREAD

**Issue by jacobeatsspam** [DanCardin/sqlalchemy-declarative-extensions#83]
What it says on the tin. I'm unable to get `drop_all` to delete views, and I don't see the method mentioned in the documentation, so I'm assuming this needs to be plumbed still.

**Comment by DanCardin** [comment]
Indeed, this is not plumbed. I'm curious what your usecase is? My only personal reason for `create_all` is tests, where I've simply never had the need.

I **expect** it will be very straightfoward to add. basically just register a on `before_drop` or whatever, and `compare_*` with a desired metadata state of a `MetaData()` with nothing registered on it.

**Comment by jacobeatsspam** [comment]
Yeah, my use case is development workflow on a remote server, where I can't easily trash the entire database instance and start over. I'm also considering whether I want these in alembic at all. Currently, when I register views for alembic, they are re-created for _every_ migration, and it's getting annoying editing every migration to remove redundant ones that haven't changed, but `create_all` issues a drop-create cycle, which is good enough for even production.

**Comment by jacobeatsspam** [comment]
> I expect it will be very straightfoward to add. basically just register a on before_drop or whatever, and compare_* with a desired metadata state of a MetaData() with nothing registered on it.

I thought the same thing, but this only deletes two of my views, which seems odd.

```python
event.listen(
            metadata,
            "before_drop",
            view_ddl(concrete_views, view_filter),
        )
```

Any guess on what I could be missing?

**Comment by DanCardin** [comment]
erm, why are they changing? i dont really understand lol.

**Comment by jacobeatsspam** [comment]
lol I'm lost too. The only thing I realized is that two of the views were deleted from the codebase and I forgot, and those are the only two being deleted. I unfortunately have to pause on this issue, but hope to investigate further in a few weeks.

**Comment by DanCardin** [comment]
Well whether or not you ultimately need it, like i said, it was straightforward to support.

**Comment by jacobeatsspam** [comment]
Tested locally and can confirm. All views dropped. I'll try to report back when I test with Procedures and Triggers. Thanks again!!
