### ISSUE TITLE
Incompatibility with alembic.autogenerate.rewriter.Rewriter

### ISSUE THREAD

**Issue by martlaf** [DanCardin/sqlalchemy-declarative-extensions#93]
Alembic provides [a Rewriter](https://alembic.sqlalchemy.org/en/latest/api/autogenerate.html#fine-grained-autogenerate-generation-with-rewriters) to enable 3rd party libraries to add custom logic to existing `ops.MigrateOperation`s. By default, if will only affect the operations which have been specifically decorated with e.g. `my_rewriter.rewrites(ops.CreateTableOp)(my_new_op)`, and the way this is done is by [declaring a no-op](https://github.com/sqlalchemy/alembic/blob/9cc68f5e89183e3c5634ac892bf7819dfc90a8d5/alembic/autogenerate/rewriter.py#L208) against all `ops.MigrateOperation`, which will be overriden by the caller for their specific use-cases.

This means that registering new operations (say `CreateSchemaOp`) that don't inherit from this `ops.MigrateOperation` are lacking the default no-op instruction, and will raise a "no dispatch function for object" ValueError on the operation when trying to autogenerate, with a stack looking like this:
```
  File "src/alembic/env.py", line 99, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/path/alembic/runtime/environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/path/alembic/runtime/migration.py", line 616, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/path/alembic/command.py", line 212, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/path/alembic/autogenerate/api.py", line 570, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/path/alembic/autogenerate/api.py", line 628, in _run_environment
    hook(migration_context, rev, self.generated_revisions)
  File "/path/alembic/autogenerate/rewriter.py", line 160, in __call__
    self.process_revision_directives(context, revision, directives)
  File "/path/alembic/autogenerate/rewriter.py", line 240, in process_revision_directives
    self._traverse_list(context, revision, directives)
  File "/path/alembic/autogenerate/rewriter.py", line 230, in _traverse_list
    dest.extend(self._traverse_for(context, revision, directive))
  File "/path/alembic/autogenerate/rewriter.py", line 219, in _traverse_for
    traverser(self, context, revision, directive)
  File "/path/alembic/autogenerate/rewriter.py", line 173, in _traverse_script
    ret = self._traverse_for(context, revision, upgrade_ops)
  File "/path/alembic/autogenerate/rewriter.py", line 219, in _traverse_for
    traverser(self, context, revision, directive)
  File "/path/alembic/autogenerate/rewriter.py", line 199, in _traverse_op_container
    self._traverse_list(context, revision, directive.ops)
  File "/path/alembic/autogenerate/rewriter.py", line 230, in _traverse_list
    dest.extend(self._traverse_for(context, revision, directive))
  File "/path/alembic/autogenerate/rewriter.py", line 218, in _traverse_for
    traverser = self._traverse.dispatch(directive)
  File "/path/alembic/util/langhelpers.py", line 299, in dispatch
    raise ValueError("no dispatch function for object: %s" % obj)
ValueError: no dispatch function for object: CreateSchemaOp(schema=Schema(name='my_schema', use_role=None), role_ops=[])
```

I haven't tried to set up a minimal reproducible example, but that shouldn't be too hard to do with just giving an empty rewriter in the alembic EnvironmentContext before running an autogenerate that should contain an sqlalchemy-declarative-extensions operation:

``` python
context.configure(
    ...,
    process_revision_directives=alembic.autogenerate.rewriter.Rewriter(),
)
```

**Comment by DanCardin** [comment]
mmm. I specifically avoided subclassing MigrateOperation to avoid polluting the whole package with alembic, so i guess i'm not surprised.

I'm not really sure what the point of this function is though. I just need to define some stub empty function with the appropriate signature and ...?

```python
Rewriter._traverse.dispatch_for(CreateSchemaOp)(some_func)
Rewriter._traverse.dispatch_for(CreateSchemaOp)(some_func)

# elsewhere
Rewriter._traverse.dispatch_for(CreateRoleOp)(some_func)
```

e.g. the actual function contents are intentionally empty because the plugin doesnt need to rewrite it's own ops?

**Comment by martlaf** [comment]
yeah I had tested something like this that worked
``` python
rewriter = alembic.autogenerate.rewriter.Rewriter()
rewriter._traverse.dispatch_for(CreateSchemaOp)(lambda *a, **k: None)
rewriter = rewriter.chain(other_rewriter)
```

But you're right, the `Dispatcher` instance is a class attribute to the `Rewriter`, meaning we don't even have to chain instances, you can just directly register the func against the `Rewriter` class and it works

**Comment by DanCardin** [comment]
I'm actually not able to reproduce it failing right now.

I'd have expected it to fail with:
```
@rewriter.Rewriter().rewrites(ops.AddColumnOp)
def add_column(*_, op):
    return op
```
in an env.py with a migrations history that produces a `CreateSchemaOp`?

I also tried rewriting `CreateSchemaOp` directly, and both appeared to not fail. Am i doing something wrong?

And now, i see the rewriter API expects (type-wise) a subclass of MigrationOperation. I wonder if i could get alembic to convert it to a protocol, because i really dont want the hard dependency on alembic tbh.

**Comment by martlaf** [comment]
You don't have to register any `rewrites` against the rewriter, but you have to specify any given rewriter on the context's `process_revision_directives` otherwise rewriting is bypassed altogether.

I could reproduce by running with trying to autogenerate using the following `env.py` against a fresh (empty) database:

``` python
import alembic.autogenerate
import sqlalchemy
from alembic import context
from dotenv import load_dotenv
from pydantic import Field
from pydantic_settings import BaseSettings
from sqlalchemy import MetaData
from sqlalchemy.orm import declarative_base
from sqlalchemy_declarative_extensions import (
    register_alembic_events,
    declare_database,
    Schemas,
)
from sqlalchemy_utils import create_database, database_exists

load_dotenv()


class ConnectionInfo(BaseSettings):
    username: str = Field(alias="PG_USERNAME")
    password: str = Field(alias="PG_PASSWORD")
    host: str = Field(alias="PG_HOST")
    port: int = Field(alias="PG_PORT")
    database: str = Field(alias="PG_DBNAME")


connection_info = ConnectionInfo()

url = sqlalchemy.URL.create(
    drivername="postgresql+psycopg2",
    username=connection_info.username,
    password=connection_info.password,
    database=connection_info.database,
    host=connection_info.host,
    port=connection_info.port,
)
engine = sqlalchemy.create_engine(url)

if not database_exists(engine.url):
    create_database(engine.url)

Base = declarative_base(metadata=MetaData(schema="myschema"))

declare_database(Base.metadata, schemas=Schemas().are(Base.metadata.schema))
register_alembic_events(views=False, rows=False)

with engine.connect() as connection:
    context.configure(
        connection=connection,
        target_metadata=Base.metadata,
        include_schemas=True,
        process_revision_directives=alembic.autogenerate.rewriter.Rewriter(),
    )
    with context.begin_transaction():
        context.run_migrations()
```
