### ISSUE TITLE
Support for reserved keywords as object names

### ISSUE THREAD

**Issue by martlaf** [DanCardin/sqlalchemy-declarative-extensions#98]
The database I'm trying to manage has a schema named `"raw"`. When I declare e.g. a grant on schema `"raw"`, grants don't seem to match during comparison. When I double-quote my schema name to `'"raw"'`, grants seem to match during comparison, but operations will be made against schema `""raw""` in the migration script.

Rephrasing, if I do this:
``` python
sqlalchemy_declarative_extensions.declare_database(
    Base.metadata,
    grants=Grants().are(DefaultGrant.on_tables_in_schema("raw").grant("select", to="my_role"))
)
```
My migration script will be filled with `ALTER DEFAULT PRIVILEGES IN SCHEMA "raw" GRANT SELECT ON TABLES TO "my_role"` instructions, trying to create grants that already exist in the database.

If, on the other hand, I do this: 
``` python
sqlalchemy_declarative_extensions.declare_database(
    Base.metadata,
    grants=Grants().are(DefaultGrant.on_tables_in_schema('"raw"').grant("select", to="my_role"))
)
```
I will only get the missing grants rendered in my migration script, but they will look like `ALTER DEFAULT PRIVILEGES IN SCHEMA ""raw"" GRANT SELECT ON TABLES TO "my_role"`, which would fail with `SQL Error [42601]: ERROR: zero-length delimited identifier at or near """"`

**Comment by DanCardin** [comment]
I tried to replicate your situation into a test, but wasn't able to make it exhibit the behavior you're describing. I wonder if you can compare my setup to what you're describing?

Also, would it be possible to paste a snippet of some of the example excess grants (with the names remapped if you need)? also also, do the excess grants go away if you upgrade?

**Comment by martlaf** [comment]
Apologies, seems like it was a misdiagnosis - I cannot reproduce anymore, unclear what change I did fixed it (but it had nothing to do with the name of the schema, had the same problem in other schemas).

**Comment by DanCardin** [comment]
fwiw, `default_grants_imply_grants=True` can sometimes emit **tons** of non-default grant statements if you haven't been using this plugin from the start (and it'll be fixing something that's actually wrong, but seems like something is wrong). also I've seen confusion between `for_role` and `to=role`, where for_role gets used on accident and cause mass rewrites of the default grants (and in this case, it's just a question of which one you want).

just some potential reasons why one might be getting large numbers of seemingly excess grants
